version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-workmail-lambda-rules"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1k628tjv2d704"
s3_prefix = "sam-workmail-lambda-rules"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Domain=\"mail2.holachilango.com\""
